import React, { useState, useEffect } from 'react';

/**
 * PayoutModal — Simulated instant payout celebration screen.
 *
 * Shown after a claim is auto-approved. Animates a counter from ₹0
 * to the payout amount, displays a fake UPI transaction reference,
 * and lets the partner "download" a receipt (opens a print dialog).
 *
 * Props:
 *   amount       — payout amount in rupees (number)
 *   txnId        — Razorpay/UPI transaction ID string
 *   partnerName  — delivery partner's name
 *   onClose      — callback to dismiss the modal
 */
export default function PayoutModal({ amount = 0, txnId = '', partnerName = 'Partner', onClose }) {
  const [displayAmount, setDisplayAmount] = useState(0);
  const [phase, setPhase] = useState('counting'); // counting | done
  const [view, setView] = useState('celebration'); // celebration | receipt

  // UPI handle derived from partner name
  const upiHandle = partnerName.toLowerCase().replace(/\s+/g, '.').slice(0, 12) + '@raksharide';
  const displayTxnId = txnId || `pay_RKSH${Date.now().toString(36).toUpperCase()}`;
  const now = new Date();
  const timestamp = now.toLocaleString('en-IN', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });

  // Animate counter from 0 → amount over ~1.2 seconds
  useEffect(() => {
    if (amount <= 0) { setDisplayAmount(0); setPhase('done'); return; }
    const DURATION_MS = 1200;
    const STEPS = 60;
    const step = amount / STEPS;
    let current = 0;
    let count = 0;
    const interval = setInterval(() => {
      count++;
      current = Math.min(amount, Math.round(step * count));
      setDisplayAmount(current);
      if (count >= STEPS) {
        clearInterval(interval);
        setPhase('done');
      }
    }, DURATION_MS / STEPS);
    return () => clearInterval(interval);
  }, [amount]);

  const handleDownloadReceipt = () => {
    const html = `
      <html><head><title>RakshaRide Payout Receipt</title>
      <style>body{font-family:sans-serif;max-width:400px;margin:40px auto;padding:24px;border:2px solid #f59e0b;border-radius:12px}
      h2{color:#f59e0b}table{width:100%}td{padding:6px 0;font-size:14px}.amount{font-size:28px;font-weight:900;color:#10b981}</style></head>
      <body>
        <h2>RakshaRide — Payout Receipt</h2>
        <hr/>
        <table>
          <tr><td><b>Partner</b></td><td>${partnerName}</td></tr>
          <tr><td><b>UPI Handle</b></td><td>${upiHandle}</td></tr>
          <tr><td><b>Transaction ID</b></td><td>${displayTxnId}</td></tr>
          <tr><td><b>Date & Time</b></td><td>${timestamp}</td></tr>
          <tr><td><b>Amount Credited</b></td><td class="amount">&#8377;${amount.toLocaleString('en-IN')}</td></tr>
        </table>
        <p style="color:#6b7280;font-size:12px;margin-top:24px">This is a simulated receipt generated by RakshaRide (OriginX — Guidewire Hackathon 2026). IRDAI Prototype.</p>
      </body></html>`;
    const win = window.open('', '_blank');
    win.document.write(html);
    win.document.close();
    win.print();
  };

  const handleOpenReceipt = () => {
    setView('receipt');
  };

  return (
    <div
      style={{
        position: 'fixed', inset: 0, zIndex: 9999,
        background: 'rgba(0,0,0,0.85)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        padding: '1rem',
        animation: 'fadeIn 0.3s ease',
      }}
      onClick={e => e.target === e.currentTarget && onClose()}
    >
      {/* Confetti ring — pure CSS radial burst */}
      {phase === 'done' && (
        <div style={{ position: 'absolute', inset: 0, pointerEvents: 'none', overflow: 'hidden' }}>
          {[...Array(16)].map((_, i) => (
            <div key={i} style={{
              position: 'absolute',
              top: '50%', left: '50%',
              width: 8, height: 8, borderRadius: '50%',
              background: ['#f59e0b','#10b981','#6366f1','#ef4444','#38bdf8'][i % 5],
              transform: `rotate(${i * 22.5}deg) translateY(-160px)`,
              animation: `confettiFall 1.4s ease-out ${i * 0.04}s both`,
            }} />
          ))}
        </div>
      )}

      <div style={{
        background: 'var(--bg-card)',
        border: '1px solid rgba(16,185,129,0.4)',
        borderRadius: 24,
        padding: '2.5rem',
        maxWidth: 420, width: '100%',
        textAlign: 'center',
        boxShadow: '0 0 80px rgba(16,185,129,0.15)',
        position: 'relative',
        animation: 'slideUp 0.4s cubic-bezier(0.34,1.56,0.64,1)',
      }}>

        {view === 'receipt' ? (
          <div style={{ textAlign: 'left' }}>
            <div style={{ fontWeight: 800, fontSize: '1.1rem', marginBottom: '0.8rem' }}>Payout Receipt</div>
            <div style={{ display: 'grid', gap: '0.55rem', fontSize: '0.85rem' }}>
              <div><strong>Partner:</strong> {partnerName}</div>
              <div><strong>UPI Handle:</strong> {upiHandle}</div>
              <div><strong>Transaction ID:</strong> <span style={{ fontFamily: 'monospace' }}>{displayTxnId}</span></div>
              <div><strong>Date & Time:</strong> {timestamp}</div>
              <div><strong>Amount:</strong> <span style={{ color: 'var(--emerald)', fontWeight: 800 }}>₹{amount.toLocaleString('en-IN')}</span></div>
            </div>
            <div style={{ display: 'flex', gap: '0.75rem', marginTop: '1.4rem' }}>
              <button className="btn btn-secondary" style={{ flex: 1 }} onClick={() => setView('celebration')}>Back</button>
              <button className="btn btn-primary" style={{ flex: 1 }} onClick={handleDownloadReceipt}>Print</button>
            </div>
          </div>
        ) : (
          <>
        {/* Success icon */}
        <div style={{
          width: 72, height: 72, borderRadius: '50%',
          background: 'radial-gradient(circle, rgba(16,185,129,0.2) 0%, transparent 70%)',
          border: '2px solid var(--emerald)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontSize: '2rem', margin: '0 auto 1.25rem',
          animation: phase === 'done' ? 'pulse 1.5s infinite' : 'none',
        }}>
          {phase === 'done' ? '' : ''}
        </div>

        <div style={{ fontSize: '0.8rem', fontWeight: 700, color: 'var(--emerald)', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: '0.5rem' }}>
          Payout Successful
        </div>

        {/* Animated amount */}
        <div style={{
          fontSize: 'clamp(2.8rem, 8vw, 4rem)',
          fontWeight: 900,
          color: 'var(--emerald)',
          letterSpacing: '-2px',
          lineHeight: 1,
          marginBottom: '0.25rem',
          fontVariantNumeric: 'tabular-nums',
        }}>
          ₹{displayAmount.toLocaleString('en-IN')}
        </div>

        <div style={{ color: 'var(--text-secondary)', fontSize: '0.875rem', marginBottom: '1.75rem' }}>
          credited to <strong style={{ color: 'var(--text-primary)' }}>{upiHandle}</strong>
        </div>

        {/* Transaction details */}
        <div style={{
          background: 'rgba(16,185,129,0.06)',
          border: '1px solid rgba(16,185,129,0.15)',
          borderRadius: 12,
          padding: '1rem',
          marginBottom: '1.5rem',
          textAlign: 'left',
        }}>
          {[
            ['Transaction ID', displayTxnId],
            ['Payment Method', 'UPI — RakshaRide Gateway'],
            ['Date & Time', timestamp],
            ['Plan', 'Parametric Weather Insurance'],
          ].map(([label, value]) => (
            <div key={label} style={{
              display: 'flex', justifyContent: 'space-between', alignItems: 'center',
              padding: '0.35rem 0',
              borderBottom: '1px solid rgba(255,255,255,0.04)',
              fontSize: '0.8rem',
            }}>
              <span style={{ color: 'var(--text-muted)' }}>{label}</span>
              <span style={{ fontFamily: label === 'Transaction ID' ? 'monospace' : 'inherit', fontWeight: 600, fontSize: label === 'Transaction ID' ? '0.72rem' : '0.8rem' }}>
                {value}
              </span>
            </div>
          ))}
        </div>

        {/* Powered by badges */}
        <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'center', marginBottom: '1.5rem' }}>
          {['Razorpay Secured', 'UPI Enabled', 'IRDAI Prototype'].map(b => (
            <span key={b} style={{
              background: 'rgba(255,255,255,0.04)',
              border: '1px solid rgba(255,255,255,0.08)',
              borderRadius: 20, padding: '0.2rem 0.65rem',
              fontSize: '0.7rem', color: 'var(--text-muted)',
            }}>{b}</span>
          ))}
        </div>

        {/* Actions */}
        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <button
            className="btn btn-secondary"
            style={{ flex: 1 }}
            onClick={handleOpenReceipt}
          >
            View Receipt
          </button>
          <button
            className="btn btn-primary"
            style={{ flex: 1 }}
            onClick={onClose}
          >
            Done
          </button>
        </div>

        <p style={{ fontSize: '0.72rem', color: 'var(--text-muted)', marginTop: '1rem' }}>
          Funds typically appear in your account within seconds.
        </p>
          </>
        )}
      </div>

      <style>{`
        @keyframes confettiFall {
          0%   { opacity: 1; transform: rotate(var(--r,0deg)) translateY(-80px) scale(1); }
          100% { opacity: 0; transform: rotate(var(--r,0deg)) translateY(-260px) scale(0.4); }
        }
      `}</style>
    </div>
  );
}
